* TODO Day 01
  - Note taken on [2021-12-19 Sun 16:50] \\
    I am getting a repeat count for the second part of the answer.
    There is some problem with boundary condition. Fix this.
  I just need to iterate through the list once. So a simple linked list would suffice.
  - Since creating the list would give me the reverse of it, I need to count the decreasing depth.
    + Hmm, it would seem that ~std::list~ allows iterating from the back too(doubly linked list).
      I will just iterate from the back for simplicity.

* DONE Day 02
  In the previous problem, when trying to read numbers sequentially, I did ~filestream >> num~. I want to do this for a complicated data structure ~filestream >> data~. What should I define for this to work?
  <2021-12-19 Sun> Got it to work. There is a bug. If the eof does not occur directly after the data, i.e., there is an extra newline, [[file:src/day02.cc::std::list<struct command> read_commands(std::string filename) {][~read_commands~]], then the program crashes trying to parse this whitespace into a ~struct command~. Now how do I tell if all that is left in the stream is whitespace?
  <2021-12-20 Mon> Solved the whitespace before eof problem by just ~peek~ and ~get~ while the ~peek~ satisfies ~isspace~.

* DONE Day 03
  I have solved a similar problem before on Average of several DNA sequences. 
  I did not use any ~lambdas~. There are instances to use ~map~ on ~std::list~, but I seem to be just using ~for~ loops.
  <2021-12-20 Mon> Something is segfaulting in part2; probably some dereferencing a bitset.
  <2021-12-21 Tue> I was deleting nodes in a list while traversing. So when I deleted a node and then used it to get the next node, the result was a segfault.

* DONE Day 04
  Finished coding the logic. Cards are not being marked at all. Needs debugging.
  - The set of marked indices is not being updated. What am I missing?
    + figured it out. I should have passed ranged over state using ~auto &~. By just using ~auto~ I was not propagating changes back to state.
  - Similar to previous day, I seem to be struggling with deleting nodes of a list while traversing it.
  I would not have struggled this much if I just tried to simulate the whole process of find the last card in my head.
